const {chromium}=require('playwright-core');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const base=process.argv.find(a=>a.startsWith('--url='))?.slice(6)||'http://localhost:3201';
const selectedWidth=process.argv.find(a=>a.startsWith('--width='))?.slice(8);
const widths=selectedWidth?[Number(selectedWidth)]:[1440,390,320,768,1024,1920,2560];
const out='/tmp/exekova-business-leaders/current';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const errors=[],results=[];try{
for(const width of widths){const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));assert.equal((await page.goto(base,{waitUntil:'domcontentloaded'})).status(),200);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,`hero-${width}.png`)});
const ribbon=await page.locator('.task-ribbon-svg').evaluate(svg=>{const r=svg.getBoundingClientRect(),input=svg.querySelector('defs path'),output=svg.querySelector('defs path:last-child');const transform=svg.getScreenCTM();const point=(p,end)=>{const pt=p.getPointAtLength(end?p.getTotalLength():0);return new DOMPoint(pt.x,pt.y).matrixTransform(transform).x;};return {left:r.left,right:r.right,width:r.width,scale:transform.a,inputStart:point(input,false),outputEnd:point(output,true)};});assert(ribbon.left<=0 && ribbon.right>=width,'Hero SVG spans viewport');if(width>=1440){assert(ribbon.inputStart<=0 && ribbon.outputEnd>=width,'Ribbon paths reach both viewport edges');assert.equal(ribbon.scale,1,'Full-width ribbon preserves text and loop scale');}
if(width>=1920){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);results.push({width,ribbon});await page.close();continue;}
await page.locator('.pricing-reference-story').scrollIntoViewIfNeeded();await page.locator('.accepted-work-meter img.chapter-photo').evaluate(img=>img.decode());await page.locator('.pricing-reference-story').screenshot({path:path.join(out,`pricing-${width}.png`)});
if(width<=700){const figure=await page.locator('.accepted-work-meter').boundingBox();for(const stat of await page.locator('.acceptance-card').all()){const r=await stat.boundingBox();assert(r.y+r.height<figure.y,'Mobile pricing figures precede the central image');}}
for(const state of ['rejected','accepted']){await page.locator(`.acceptance-card[data-outcome=${state}]`).click();assert.equal(await page.locator('.accepted-work-meter').getAttribute('data-outcome'),state);assert.equal(await page.locator('[data-meter-amount]').textContent(),state==='accepted'?'$19USD':'$0USD');}await page.getByRole('button',{name:'Show rejected attempt',exact:true}).click();assert.equal(await page.locator('[data-meter-units]').textContent(),'0');
await page.locator('.pricing-detail summary').click();assert((await page.locator('.pricing-detail').innerText()).includes('Pull request with evidence'));await page.locator('.pricing-detail summary').click();
await page.locator('#team-title').evaluate(e=>scrollTo({top:scrollY+e.getBoundingClientRect().top-120,behavior:'instant'}));await page.screenshot({path:path.join(out,`team-heading-${width}.png`)});
const roles=await page.locator('.team-role-buttons button').allTextContents();for(const role of roles){await page.locator('.team-role-buttons').getByRole('button',{name:role,exact:true}).click();assert.equal(await page.locator('.team-value-panel').getAttribute('data-role'),role);}
if(width>900){await page.locator('.team-role-buttons').getByRole('button',{name:'CEO',exact:true}).click();await page.locator('.team-value-panel img.chapter-photo').evaluate(img=>img.decode());await page.screenshot({path:path.join(out,`team-scene-${width}.png`)});const box=await page.locator('.team-outcome-visual:visible').boundingBox();assert(Math.abs(box.width-box.height)<2,'Team image is square');}
else {const row=page.locator('.team-role-story').first();await row.scrollIntoViewIfNeeded();await row.locator('img.chapter-photo').evaluate(img=>img.decode());await row.screenshot({path:path.join(out,`team-scene-${width}.png`)});}
assert.equal(await page.locator('.industry-card').count(),13);await page.locator('#industries-title').evaluate(e=>scrollTo({top:scrollY+e.getBoundingClientRect().top-120,behavior:'instant'}));await page.screenshot({path:path.join(out,`industry-heading-${width}.png`)});
for(const i of [0,1,2]){const group=page.locator('.industry-group').nth(i);await group.scrollIntoViewIfNeeded();if(i===0)await group.locator('img.chapter-photo').evaluate(img=>img.decode());await group.screenshot({path:path.join(out,`industry-${i}-${width}.png`)});}
await page.locator('.industry-delivery-grid').scrollIntoViewIfNeeded();await page.locator('.industry-delivery-visual img.chapter-photo').evaluate(img=>img.decode());await page.locator('.industry-delivery-grid').screenshot({path:path.join(out,`industry-delivery-${width}.png`)});
const receipt=await page.locator('.industry-acceptance-receipt').boundingBox();for(const check of await page.locator('.industry-window-main li').all()){const r=await check.boundingBox();assert(r.x>=receipt.x+receipt.width || r.x+r.width<=receipt.x || r.y>=receipt.y+receipt.height || r.y+r.height<=receipt.y,`Evidence stays clear of foreground record at ${width}`);}
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width,`Page overflow at ${width}`);
const geometry=await page.evaluate(()=>Object.fromEntries(['.team-outcome-visual','.accepted-work-meter','.industry-story-visual','.industry-delivery-visual'].map(selector=>{const el=[...document.querySelectorAll(selector)].find(e=>e.getBoundingClientRect().width>0),r=el.getBoundingClientRect();return [selector,{width:r.width,height:r.height,radius:getComputedStyle(el).borderRadius}];})));
if(width===1440){for(const [selector,w,h,radius] of [['.team-outcome-visual',620,620,'24px'],['.accepted-work-meter',296,296,'24px'],['.industry-story-visual',667.2,736,'40px'],['.industry-delivery-visual',707.6,738,'40px']]){assert(Math.abs(geometry[selector].width-w)<1,selector+' reference width');assert(Math.abs(geometry[selector].height-h)<1,selector+' reference height');assert.equal(geometry[selector].radius,radius,selector+' reference corners');}}
if(width>900){await page.emulateMedia({reducedMotion:'no-preference'});for(const [index,role] of roles.entries()){await page.locator('.team-role-story').nth(index).evaluate(e=>scrollTo({top:scrollY+e.getBoundingClientRect().top+e.offsetHeight/2-innerHeight/2,behavior:'instant'}));await page.waitForTimeout(250);assert.equal(await page.locator('.team-value-panel').getAttribute('data-role'),role,'Scroll follows '+role);}}
results.push({width,ribbon,geometry});await page.close();console.log('PASS chapters',width);}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,selectedWidth?`results-${selectedWidth}.json`:'results.json'),JSON.stringify({results,errors},null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
