const {chromium}=require('playwright-core');
const fs=require('fs');const path=require('path');const assert=require('node:assert/strict');
const base=process.argv.find(arg=>arg.startsWith('--url='))?.slice(6)||process.env.BETA_QA_URL||'http://localhost:3203';
const selectedWidth=process.argv.find(arg=>arg.startsWith('--width='))?.split('=')[1];
const widths=selectedWidth?[Number(selectedWidth)]:[1440,390,320,768,1024];
const out='/tmp/exekova-flow-review/current';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const errors=[];try{
for(const width of widths){const p=await browser.newPage({viewport:{width,height:1000},reducedMotion:'no-preference'});p.on('pageerror',e=>errors.push(e.message));await p.goto(base,{waitUntil:'domcontentloaded'});await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(out,`hero-${width}.png`)});
try{await p.waitForFunction(()=>document.querySelector('.task-ribbon')?.dataset.playing==='true' && Number(document.querySelector('.ribbon-output-copy textPath')?.getAttribute('startOffset'))<0);}catch(error){console.error('Hero animation state',await p.evaluate(()=>({hidden:document.hidden,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,playing:document.querySelector('.task-ribbon')?.dataset.playing,offset:document.querySelector('.ribbon-output-copy textPath')?.getAttribute('startOffset'),bounds:document.querySelector('.task-ribbon')?.getBoundingClientRect().toJSON()})));throw error;}
const input=p.locator(width<=700?'.ribbon-input-mobile textPath':'.ribbon-input-copy:not(.ribbon-input-mobile) textPath');const output=p.locator('.ribbon-output-copy textPath');const a=Number(await input.getAttribute('startOffset')),b=Number(await output.getAttribute('startOffset'));await p.waitForTimeout(200);assert(Number(await input.getAttribute('startOffset'))>a,'Input flows into EXEKOVA');assert(Number(await output.getAttribute('startOffset'))>b,'Output flows away from EXEKOVA');
await p.locator('.product-comparison-scroll').evaluate(el=>scrollTo({top:scrollY+el.getBoundingClientRect().top-120,behavior:'instant'}));
if(width<=700 && await p.locator('.mobile-access-bar').count())await p.getByRole('button',{name:'Dismiss access bar'}).click();
await p.waitForFunction(()=>document.querySelector('.flow-screen')?.dataset.playing==='true');await p.locator('.flow-screen .work-backdrop').evaluate(img=>img.decode());
await p.screenshot({path:path.join(out,`flow-task-${width}.png`)});
await p.waitForFunction(()=>document.querySelector('.flow-screen')?.dataset.stage==='repo',null,{timeout:6000});await p.screenshot({path:path.join(out,`flow-repo-${width}.png`)});
await p.waitForFunction(()=>document.querySelector('.flow-screen')?.dataset.stage==='outcome' && document.querySelector('.flow-screen')?.dataset.complete==='false',null,{timeout:6000});assert.equal(await p.locator('.flow-screen .work-evidence [data-passed=true]').count(),0);await p.screenshot({path:path.join(out,`flow-review-${width}.png`)});
await p.waitForFunction(()=>document.querySelector('.flow-screen')?.dataset.playing==='false' && document.querySelector('.flow-screen')?.dataset.complete==='true',null,{timeout:7000});assert.equal(await p.locator('.flow-screen .work-evidence [data-passed=true]').count(),3);await p.screenshot({path:path.join(out,`flow-done-${width}.png`)});
await p.getByRole('button',{name:'Replay workflow preview',exact:true}).click();await p.getByRole('button',{name:'Pause workflow preview',exact:true}).click();const paused=await p.locator('.flow-task-stream textPath').getAttribute('startOffset');await p.waitForTimeout(500);assert.equal(await p.locator('.flow-task-stream textPath').getAttribute('startOffset'),paused);
if(width>900){for(const amount of [.5,.95]){await p.locator('.product-comparison-scroll').evaluate((el,amount)=>scrollTo({top:scrollY+el.getBoundingClientRect().top-120+(el.offsetHeight-700+120)*amount,behavior:'instant'}),amount);await p.waitForTimeout(250);await p.screenshot({path:path.join(out,`flow-morph-${width}-${amount}.png`)});}
await p.locator('.flow-preview-controls button').nth(2).evaluate(button=>button.click());await p.waitForTimeout(900);
const panel=await p.locator('.flow-screen').boundingBox();assert(Math.abs(panel.width-400)<2,'Expanded panel contracts to 400px');assert(Math.abs(panel.height-466)<2,'Portrait scene is 466px high');
const branch=await p.locator('.flow-screen .work-branch').boundingBox(),sticker=await p.locator('.flow-screen .work-status-sticker').boundingBox();assert(branch.y+branch.height<=sticker.y,'Compact outcome footer stays clear of status badge');
await p.screenshot({path:path.join(out,`flow-morph-done-${width}.png`)});}
await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.flow-screen').getAttribute('data-playing'),'false');
if(width<=700){for(const [i,scene] of (await p.locator('.how-mobile-scene').all()).entries()){await scene.scrollIntoViewIfNeeded();await scene.locator('img.work-backdrop').evaluate(img=>img.decode());await scene.screenshot({path:path.join(out,`how-${i}-${width}.png`)});}}else{for(const i of [0,1,2]){await p.locator('.how-story-tabs button').nth(i).click();await p.locator('.how-story').screenshot({path:path.join(out,`how-${i}-${width}.png`)});}}
const pageWidth=await p.evaluate(()=>document.documentElement.scrollWidth);if(pageWidth!==width){console.error('Overflow details',await p.evaluate(()=>[...document.querySelectorAll('body *')].filter(el=>el instanceof HTMLElement&&el.getBoundingClientRect().right>innerWidth+1).filter(el=>{for(let parent=el.parentElement;parent&&parent!==document.body;parent=parent.parentElement){if(getComputedStyle(parent).overflowX!=='visible'&&parent.getBoundingClientRect().right<=innerWidth+1)return false;}return true;}).map(el=>({tag:el.tagName,class:el.className,width:el.getBoundingClientRect().width,right:el.getBoundingClientRect().right,overflow:getComputedStyle(el).overflow,position:getComputedStyle(el).position,visibility:getComputedStyle(el).visibility,parent:el.parentElement.className}))));await p.screenshot({path:path.join(out,`overflow-${width}.png`)});}assert.equal(pageWidth,width,`Overflow ${width}`);await p.close();console.log('PASS flow',width);}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,selectedWidth?`results-${selectedWidth}.json`:'results.json'),JSON.stringify({widths,direction:'pass',sequence:'pass',gating:'pass',pause:'pass',reducedMotion:'pass',errors},null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
